// 20230508110502
// https://34.229.155.92:8000/api/test

countries = [
    {
      "commonName": "Spain",
      "officialName": "Kingdom of Spain",
      "code": "ES",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/es.png",
      "continent": "Europe",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/138JaXW8EZzRVitY9",
      "flagIcon": "🇪🇸",
      "capital": "Madrid",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Afghanistan",
      "officialName": "Islamic Republic of Afghanistan",
      "code": "AF",
      "region": "Asia",
      "flag": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
      "continent": "Asia",
      "timezone": "UTC+04:30",
      "locationInMap": "https://goo.gl/maps/BXBGw7yUUFknCfva9",
      "flagIcon": "🇦🇫",
      "capital": "Kabul",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Sudan",
      "officialName": "Republic of the Sudan",
      "code": "SD",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sd.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/bNW7YUJCaqR8zcXn7",
      "flagIcon": "🇸🇩",
      "capital": "Khartoum",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Bulgaria",
      "officialName": "Republic of Bulgaria",
      "code": "BG",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/bg.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/F5uAhDGWzc3BrHfm9",
      "flagIcon": "🇧🇬",
      "capital": "Sofia",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Germany",
      "officialName": "Federal Republic of Germany",
      "code": "DE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/de.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/mD9FBMq1nvXUBrkv6",
      "flagIcon": "🇩🇪",
      "capital": "Berlin",
      "subregion": "Western Europe"
    },
    {
      "commonName": "Lithuania",
      "officialName": "Republic of Lithuania",
      "code": "LT",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/lt.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/dd1s9rrLjrK2G8yY6",
      "flagIcon": "🇱🇹",
      "capital": "Vilnius",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Mayotte",
      "officialName": "Department of Mayotte",
      "code": "YT",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/yt.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/1e7MXmfBwQv3TQGF7",
      "flagIcon": "🇾🇹",
      "capital": "Mamoudzou",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Marshall Islands",
      "officialName": "Republic of the Marshall Islands",
      "code": "MH",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/mh.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/A4xLi1XvcX88gi3W8",
      "flagIcon": "🇲🇭",
      "capital": "Majuro",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Poland",
      "officialName": "Republic of Poland",
      "code": "PL",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/pl.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/gY9Xw4Sf4415P4949",
      "flagIcon": "🇵🇱",
      "capital": "Warsaw",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Tokelau",
      "officialName": "Tokelau",
      "code": "TK",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/tk.png",
      "continent": "Oceania",
      "timezone": "UTC+13:00",
      "locationInMap": "https://goo.gl/maps/Ap5qN8qien6pT9UN6",
      "flagIcon": "🇹🇰",
      "capital": "Fakaofo",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Tanzania",
      "officialName": "United Republic of Tanzania",
      "code": "TZ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/tz.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/NWYMqZYXte4zGZ2Q8",
      "flagIcon": "🇹🇿",
      "capital": "Dodoma",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Timor-Leste",
      "officialName": "Democratic Republic of Timor-Leste",
      "code": "TL",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/tl.png",
      "continent": "Oceania",
      "timezone": "UTC+09:00",
      "locationInMap": "https://goo.gl/maps/sFqBC9zjgUXPR1iTA",
      "flagIcon": "🇹🇱",
      "capital": "Dili",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Togo",
      "officialName": "Togolese Republic",
      "code": "TG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/tg.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/jzAa9feXuXPrKVb89",
      "flagIcon": "🇹🇬",
      "capital": "Lomé",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Czechia",
      "officialName": "Czech Republic",
      "code": "CZ",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/cz.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/47dmgeXMZyhDHyQW8",
      "flagIcon": "🇨🇿",
      "capital": "Prague",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Monaco",
      "officialName": "Principality of Monaco",
      "code": "MC",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/mc.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/DGpndDot28bYdXYn7",
      "flagIcon": "🇲🇨",
      "capital": "Monaco",
      "subregion": "Western Europe"
    },
    {
      "commonName": "Uganda",
      "officialName": "Republic of Uganda",
      "code": "UG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ug.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/Y7812hFiGa8LD9N68",
      "flagIcon": "🇺🇬",
      "capital": "Kampala",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Trinidad and Tobago",
      "officialName": "Republic of Trinidad and Tobago",
      "code": "TT",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/tt.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/NrRfDEWoG8FGZqWY7",
      "flagIcon": "🇹🇹",
      "capital": "Port of Spain",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Algeria",
      "officialName": "People's Democratic Republic of Algeria",
      "code": "DZ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/dz.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/RsAyAfyaiNVb8DpW8",
      "flagIcon": "🇩🇿",
      "capital": "Algiers",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Ukraine",
      "officialName": "Ukraine",
      "code": "UA",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ua.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/DvgJMiPJ7aozKFZv7",
      "flagIcon": "🇺🇦",
      "capital": "Kyiv",
      "subregion": "Eastern Europe"
    },
    {
      "commonName": "Estonia",
      "officialName": "Republic of Estonia",
      "code": "EE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ee.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/6SsynwGUodL1sDvq8",
      "flagIcon": "🇪🇪",
      "capital": "Tallinn",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Greece",
      "officialName": "Hellenic Republic",
      "code": "GR",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/gr.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/LHGcAvuRyD2iKECC6",
      "flagIcon": "🇬🇷",
      "capital": "Athens",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Mauritania",
      "officialName": "Islamic Republic of Mauritania",
      "code": "MR",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/mr.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/im2MmQ5jFjzxWBks5",
      "flagIcon": "🇲🇷",
      "capital": "Nouakchott",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Georgia",
      "officialName": "Georgia",
      "code": "GE",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ge.png",
      "continent": "Asia",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/bvCaGBePR1ZEDK5cA",
      "flagIcon": "🇬🇪",
      "capital": "Tbilisi",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Sint Maarten",
      "officialName": "Sint Maarten",
      "code": "SX",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/sx.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/DjvcESy1a1oGEZuNA",
      "flagIcon": "🇸🇽",
      "capital": "Philipsburg",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Namibia",
      "officialName": "Republic of Namibia",
      "code": "NA",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/na.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/oR1i8BFEYX3EY83WA",
      "flagIcon": "🇳🇦",
      "capital": "Windhoek",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "North Macedonia",
      "officialName": "Republic of North Macedonia",
      "code": "MK",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/mk.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/55Q8MEnF6ACdu3q79",
      "flagIcon": "🇲🇰",
      "capital": "Skopje",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Mauritius",
      "officialName": "Republic of Mauritius",
      "code": "MU",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/mu.png",
      "continent": "Africa",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/PpKtZ4W3tir5iGrz7",
      "flagIcon": "🇲🇺",
      "capital": "Port Louis",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Kiribati",
      "officialName": "Independent and Sovereign Republic of Kiribati",
      "code": "KI",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/ki.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/NBfYvrndW4skAimw9",
      "flagIcon": "🇰🇮",
      "capital": "South Tarawa",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Republic of the Congo",
      "officialName": "Republic of the Congo",
      "code": "CG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/cg.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/Phf5dDDKdfCtuBTb6",
      "flagIcon": "🇨🇬",
      "capital": "Brazzaville",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Equatorial Guinea",
      "officialName": "Republic of Equatorial Guinea",
      "code": "GQ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/gq.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/ucWfFd8aW1FbGMva9",
      "flagIcon": "🇬🇶",
      "capital": "Malabo",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Niue",
      "officialName": "Niue",
      "code": "NU",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/nu.png",
      "continent": "Oceania",
      "timezone": "UTC-11:00",
      "locationInMap": "https://goo.gl/maps/xFgdzs3E55Rk1y8P9",
      "flagIcon": "🇳🇺",
      "capital": "Alofi",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Kosovo",
      "officialName": "Republic of Kosovo",
      "code": "XK",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/xk.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/CSC4Yc8SWPgburuD9",
      "flagIcon": "🇽🇰",
      "capital": "Pristina",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Palau",
      "officialName": "Republic of Palau",
      "code": "PW",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/pw.png",
      "continent": "Oceania",
      "timezone": "UTC+09:00",
      "locationInMap": "https://goo.gl/maps/MVasQBbUkQP7qQDR9",
      "flagIcon": "🇵🇼",
      "capital": "Ngerulmud",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Qatar",
      "officialName": "State of Qatar",
      "code": "QA",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/qa.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/ZV76Y49z7LLUZ2KQ6",
      "flagIcon": "🇶🇦",
      "capital": "Doha",
      "subregion": "Western Asia"
    },
    {
      "commonName": "United States",
      "officialName": "United States of America",
      "code": "US",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/us.png",
      "continent": "North America",
      "timezone": "UTC-12:00",
      "locationInMap": "https://goo.gl/maps/e8M246zY4BSjkjAv6",
      "flagIcon": "🇺🇸",
      "capital": "Washington, D.C.",
      "subregion": "North America"
    },
    {
      "commonName": "Cayman Islands",
      "officialName": "Cayman Islands",
      "code": "KY",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ky.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/P3ZVXX3LH63t91hL8",
      "flagIcon": "🇰🇾",
      "capital": "George Town",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Botswana",
      "officialName": "Republic of Botswana",
      "code": "BW",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/bw.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/E364KeLy6N4JwxwQ8",
      "flagIcon": "🇧🇼",
      "capital": "Gaborone",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "Palestine",
      "officialName": "State of Palestine",
      "code": "PS",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ps.png",
      "continent": "Asia",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/QvTbkRdmdWEoYAmt5",
      "flagIcon": "🇵🇸",
      "capital": "Ramallah",
      "subregion": "Western Asia"
    },
    {
      "commonName": "South Africa",
      "officialName": "Republic of South Africa",
      "code": "ZA",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/za.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/CLCZ1R8Uz1KpYhRv6",
      "flagIcon": "🇿🇦",
      "capital": "Pretoria",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "Vietnam",
      "officialName": "Socialist Republic of Vietnam",
      "code": "VN",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/vn.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/PCpVt9WzdJ9A9nEZ9",
      "flagIcon": "🇻🇳",
      "capital": "Hanoi",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Jersey",
      "officialName": "Bailiwick of Jersey",
      "code": "JE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/je.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/rXG8GZZtsqK92kTCA",
      "flagIcon": "🇯🇪",
      "capital": "Saint Helier",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Guyana",
      "officialName": "Co-operative Republic of Guyana",
      "code": "GY",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gy.png",
      "continent": "South America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/DFsme2xEeugUAsCx5",
      "flagIcon": "🇬🇾",
      "capital": "Georgetown",
      "subregion": "South America"
    },
    {
      "commonName": "Tuvalu",
      "officialName": "Tuvalu",
      "code": "TV",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/tv.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/LbuUxtkgm1dfN1Pn6",
      "flagIcon": "🇹🇻",
      "capital": "Funafuti",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Jordan",
      "officialName": "Hashemite Kingdom of Jordan",
      "code": "JO",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/jo.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/ko1dzSDKg8Gsi9A98",
      "flagIcon": "🇯🇴",
      "capital": "Amman",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Papua New Guinea",
      "officialName": "Independent State of Papua New Guinea",
      "code": "PG",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/pg.png",
      "continent": "Oceania",
      "timezone": "UTC+10:00",
      "locationInMap": "https://goo.gl/maps/ChGmzZBjZ3vnBwR2A",
      "flagIcon": "🇵🇬",
      "capital": "Port Moresby",
      "subregion": "Melanesia"
    },
    {
      "commonName": "Bahamas",
      "officialName": "Commonwealth of the Bahamas",
      "code": "BS",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bs.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/1YzRs1BZrG8p8pmVA",
      "flagIcon": "🇧🇸",
      "capital": "Nassau",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Cape Verde",
      "officialName": "Republic of Cabo Verde",
      "code": "CV",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/cv.png",
      "continent": "Africa",
      "timezone": "UTC-01:00",
      "locationInMap": "https://goo.gl/maps/Kc9vy5ChjuiAgMfXA",
      "flagIcon": "🇨🇻",
      "capital": "Praia",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Oman",
      "officialName": "Sultanate of Oman",
      "code": "OM",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/om.png",
      "continent": "Asia",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/L2BoXoAwDDwWecnw5",
      "flagIcon": "🇴🇲",
      "capital": "Muscat",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Venezuela",
      "officialName": "Bolivarian Republic of Venezuela",
      "code": "VE",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ve.png",
      "continent": "South America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/KLCwDN8sec7z2kse9",
      "flagIcon": "🇻🇪",
      "capital": "Caracas",
      "subregion": "South America"
    },
    {
      "commonName": "Bolivia",
      "officialName": "Plurinational State of Bolivia",
      "code": "BO",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bo.png",
      "continent": "South America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/9DfnyfbxNM2g5U9b9",
      "flagIcon": "🇧🇴",
      "capital": "Sucre",
      "subregion": "South America"
    },
    {
      "commonName": "Egypt",
      "officialName": "Arab Republic of Egypt",
      "code": "EG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/eg.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/uoDRhXbsqjG6L7VG7",
      "flagIcon": "🇪🇬",
      "capital": "Cairo",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Canada",
      "officialName": "Canada",
      "code": "CA",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ca.png",
      "continent": "North America",
      "timezone": "UTC-08:00",
      "locationInMap": "https://goo.gl/maps/jmEVLugreeqiZXxbA",
      "flagIcon": "🇨🇦",
      "capital": "Ottawa",
      "subregion": "North America"
    },
    {
      "commonName": "Norway",
      "officialName": "Kingdom of Norway",
      "code": "NO",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/no.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/htWRrphA7vNgQNdSA",
      "flagIcon": "🇳🇴",
      "capital": "Oslo",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Kyrgyzstan",
      "officialName": "Kyrgyz Republic",
      "code": "KG",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kg.png",
      "continent": "Asia",
      "timezone": "UTC+06:00",
      "locationInMap": "https://goo.gl/maps/SKG8BSMMQVvxkRkB7",
      "flagIcon": "🇰🇬",
      "capital": "Bishkek",
      "subregion": "Central Asia"
    },
    {
      "commonName": "Armenia",
      "officialName": "Republic of Armenia",
      "code": "AM",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/am.png",
      "continent": "Asia",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/azWUtK9bUQYEyccbA",
      "flagIcon": "🇦🇲",
      "capital": "Yerevan",
      "subregion": "Western Asia"
    },
    {
      "commonName": "DR Congo",
      "officialName": "Democratic Republic of the Congo",
      "code": "CD",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/cd.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/KfhNVn6VqdZXWu8n9",
      "flagIcon": "🇨🇩",
      "capital": "Kinshasa",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Puerto Rico",
      "officialName": "Commonwealth of Puerto Rico",
      "code": "PR",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/pr.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/sygfDbtwn389wu8x5",
      "flagIcon": "🇵🇷",
      "capital": "San Juan",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Liechtenstein",
      "officialName": "Principality of Liechtenstein",
      "code": "LI",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/li.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/KNuHeiJzAPodwM7y6",
      "flagIcon": "🇱🇮",
      "capital": "Vaduz",
      "subregion": "Western Europe"
    },
    {
      "commonName": "Eswatini",
      "officialName": "Kingdom of Eswatini",
      "code": "SZ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sz.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/cUY79eqQihFSE8hV6",
      "flagIcon": "🇸🇿",
      "capital": "Mbabane",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "Faroe Islands",
      "officialName": "Faroe Islands",
      "code": "FO",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/fo.png",
      "continent": "Europe",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/6sTru4SmHdEVcNkM6",
      "flagIcon": "🇫🇴",
      "capital": "Tórshavn",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Nigeria",
      "officialName": "Federal Republic of Nigeria",
      "code": "NG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ng.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/LTn417qWwBPFszuV9",
      "flagIcon": "🇳🇬",
      "capital": "Abuja",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Saint Martin",
      "officialName": "Saint Martin",
      "code": "MF",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/mf.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/P9ho9QuJ9EAR28JEA",
      "flagIcon": "🇲🇫",
      "capital": "Marigot",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Guam",
      "officialName": "Guam",
      "code": "GU",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/gu.png",
      "continent": "Oceania",
      "timezone": "UTC+10:00",
      "locationInMap": "https://goo.gl/maps/Xfnq2i279b18cH3C9",
      "flagIcon": "🇬🇺",
      "capital": "Hagåtña",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Malawi",
      "officialName": "Republic of Malawi",
      "code": "MW",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/mw.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/mc6z83pW9m98X2Ef6",
      "flagIcon": "🇲🇼",
      "capital": "Lilongwe",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Åland Islands",
      "officialName": "Åland Islands",
      "code": "AX",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ax.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/ewFb3vYsfUmVCoSb8",
      "flagIcon": "🇦🇽",
      "capital": "Mariehamn",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "São Tomé and Príncipe",
      "officialName": "Democratic Republic of São Tomé and Príncipe",
      "code": "ST",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/st.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/9EUppm13RtPX9oF46",
      "flagIcon": "🇸🇹",
      "capital": "São Tomé",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Falkland Islands",
      "officialName": "Falkland Islands",
      "code": "FK",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/fk.png",
      "continent": "South America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/TZH1x7AGanQKifNk7",
      "flagIcon": "🇫🇰",
      "capital": "Stanley",
      "subregion": "South America"
    },
    {
      "commonName": "Guatemala",
      "officialName": "Republic of Guatemala",
      "code": "GT",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gt.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/JoRAbem4Hxb9FYbVA",
      "flagIcon": "🇬🇹",
      "capital": "Guatemala City",
      "subregion": "Central America"
    },
    {
      "commonName": "Barbados",
      "officialName": "Barbados",
      "code": "BB",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bb.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/2m36v8STvbGAWd9c7",
      "flagIcon": "🇧🇧",
      "capital": "Bridgetown",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Ghana",
      "officialName": "Republic of Ghana",
      "code": "GH",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/gh.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/Avy5RSmdsXFBaiXq8",
      "flagIcon": "🇬🇭",
      "capital": "Accra",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Nicaragua",
      "officialName": "Republic of Nicaragua",
      "code": "NI",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ni.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/P77LaEVkKJKXneRC6",
      "flagIcon": "🇳🇮",
      "capital": "Managua",
      "subregion": "Central America"
    },
    {
      "commonName": "Isle of Man",
      "officialName": "Isle of Man",
      "code": "IM",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/im.png",
      "continent": "Europe",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/4DqVHDgVaFgnh8ZV8",
      "flagIcon": "🇮🇲",
      "capital": "Douglas",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Portugal",
      "officialName": "Portuguese Republic",
      "code": "PT",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/pt.png",
      "continent": "Europe",
      "timezone": "UTC-01:00",
      "locationInMap": "https://goo.gl/maps/BaTBSyc4GWMmbAKB8",
      "flagIcon": "🇵🇹",
      "capital": "Lisbon",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Angola",
      "officialName": "Republic of Angola",
      "code": "AO",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ao.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/q42Qbf1BmQL3fuZg9",
      "flagIcon": "🇦🇴",
      "capital": "Luanda",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Dominican Republic",
      "officialName": "Dominican Republic",
      "code": "DO",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/do.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/soxooTHxEeiAbn3UA",
      "flagIcon": "🇩🇴",
      "capital": "Santo Domingo",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Albania",
      "officialName": "Republic of Albania",
      "code": "AL",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/al.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/BzN9cTuj68ZA8SyZ8",
      "flagIcon": "🇦🇱",
      "capital": "Tirana",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Guinea-Bissau",
      "officialName": "Republic of Guinea-Bissau",
      "code": "GW",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/gw.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/5Wyaz17miUc1zLc67",
      "flagIcon": "🇬🇼",
      "capital": "Bissau",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Libya",
      "officialName": "State of Libya",
      "code": "LY",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ly.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/eLgGnaQWcJEdYRMy5",
      "flagIcon": "🇱🇾",
      "capital": "Tripoli",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Kuwait",
      "officialName": "State of Kuwait",
      "code": "KW",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kw.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/aqr3aNQjS1BAvksJ7",
      "flagIcon": "🇰🇼",
      "capital": "Kuwait City",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Bahrain",
      "officialName": "Kingdom of Bahrain",
      "code": "BH",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/bh.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/5Zue99Zc6vFBHxzJ7",
      "flagIcon": "🇧🇭",
      "capital": "Manama",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Turkmenistan",
      "officialName": "Turkmenistan",
      "code": "TM",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/tm.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/cgfUcaQHSWKuqeKk9",
      "flagIcon": "🇹🇲",
      "capital": "Ashgabat",
      "subregion": "Central Asia"
    },
    {
      "commonName": "Liberia",
      "officialName": "Republic of Liberia",
      "code": "LR",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/lr.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/4VsHsc2oeGeRL3wg6",
      "flagIcon": "🇱🇷",
      "capital": "Monrovia",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Burkina Faso",
      "officialName": "Burkina Faso",
      "code": "BF",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/bf.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/rKRmpcMbFher2ozb7",
      "flagIcon": "🇧🇫",
      "capital": "Ouagadougou",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Latvia",
      "officialName": "Republic of Latvia",
      "code": "LV",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/lv.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/iQpUkH7ghq31ZtXe9",
      "flagIcon": "🇱🇻",
      "capital": "Riga",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Russia",
      "officialName": "Russian Federation",
      "code": "RU",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ru.png",
      "continent": "Europe",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/4F4PpDhGJgVvLby57",
      "flagIcon": "🇷🇺",
      "capital": "Moscow",
      "subregion": "Eastern Europe"
    },
    {
      "commonName": "Philippines",
      "officialName": "Republic of the Philippines",
      "code": "PH",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ph.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/k8T2fb5VMUfsWFX6A",
      "flagIcon": "🇵🇭",
      "capital": "Manila",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "New Zealand",
      "officialName": "New Zealand",
      "code": "NZ",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/nz.png",
      "continent": "Oceania",
      "timezone": "UTC-11:00",
      "locationInMap": "https://goo.gl/maps/xXiDQo65dwdpw9iu8",
      "flagIcon": "🇳🇿",
      "capital": "Wellington",
      "subregion": "Australia and New Zealand"
    },
    {
      "commonName": "Cameroon",
      "officialName": "Republic of Cameroon",
      "code": "CM",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/cm.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/JqiipHgFboG3rBJh9",
      "flagIcon": "🇨🇲",
      "capital": "Yaoundé",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Ecuador",
      "officialName": "Republic of Ecuador",
      "code": "EC",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ec.png",
      "continent": "South America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/TbX8hUW4gcbRPZiK7",
      "flagIcon": "🇪🇨",
      "capital": "Quito",
      "subregion": "South America"
    },
    {
      "commonName": "Anguilla",
      "officialName": "Anguilla",
      "code": "AI",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ai.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/3KgLnEyN7amdno2p9",
      "flagIcon": "🇦🇮",
      "capital": "The Valley",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Romania",
      "officialName": "Romania",
      "code": "RO",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ro.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/845hAgCf1mDkN3vr7",
      "flagIcon": "🇷🇴",
      "capital": "Bucharest",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "India",
      "officialName": "Republic of India",
      "code": "IN",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/in.png",
      "continent": "Asia",
      "timezone": "UTC+05:30",
      "locationInMap": "https://goo.gl/maps/WSk3fLwG4vtPQetp7",
      "flagIcon": "🇮🇳",
      "capital": "New Delhi",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Gabon",
      "officialName": "Gabonese Republic",
      "code": "GA",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ga.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/vyRSkqw1H1fnq4ry6",
      "flagIcon": "🇬🇦",
      "capital": "Libreville",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Myanmar",
      "officialName": "Republic of the Union of Myanmar",
      "code": "MM",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/mm.png",
      "continent": "Asia",
      "timezone": "UTC+06:30",
      "locationInMap": "https://goo.gl/maps/4jrZyJkDERUfHyp26",
      "flagIcon": "🇲🇲",
      "capital": "Naypyidaw",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Réunion",
      "officialName": "Réunion Island",
      "code": "RE",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/re.png",
      "continent": "Africa",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/wWpBrXsp8UHVbah29",
      "flagIcon": "🇷🇪",
      "capital": "Saint-Denis",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "American Samoa",
      "officialName": "American Samoa",
      "code": "AS",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/as.png",
      "continent": "Oceania",
      "timezone": "UTC-11:00",
      "locationInMap": "https://goo.gl/maps/Re9ePMjwP1sFCBFA6",
      "flagIcon": "🇦🇸",
      "capital": "Pago Pago",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Montenegro",
      "officialName": "Montenegro",
      "code": "ME",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/me.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/4THX1fM7WqANuPbB8",
      "flagIcon": "🇲🇪",
      "capital": "Podgorica",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Belize",
      "officialName": "Belize",
      "code": "BZ",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bz.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/jdCccpdLodm1uTmo9",
      "flagIcon": "🇧🇿",
      "capital": "Belmopan",
      "subregion": "Central America"
    },
    {
      "commonName": "Mongolia",
      "officialName": "Mongolia",
      "code": "MN",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/mn.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/A1X7bMCKThBDNjzH6",
      "flagIcon": "🇲🇳",
      "capital": "Ulan Bator",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "Austria",
      "officialName": "Republic of Austria",
      "code": "AT",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/at.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/pCWpWQhznHyRzQcu9",
      "flagIcon": "🇦🇹",
      "capital": "Vienna",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Montserrat",
      "officialName": "Montserrat",
      "code": "MS",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ms.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/CSbe7UmxPmiwQB7GA",
      "flagIcon": "🇲🇸",
      "capital": "Plymouth",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Saudi Arabia",
      "officialName": "Kingdom of Saudi Arabia",
      "code": "SA",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/sa.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/5PSjvdJ1AyaLFRrG9",
      "flagIcon": "🇸🇦",
      "capital": "Riyadh",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Hungary",
      "officialName": "Hungary",
      "code": "HU",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/hu.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/9gfPupm5bffixiFJ6",
      "flagIcon": "🇭🇺",
      "capital": "Budapest",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Nauru",
      "officialName": "Republic of Nauru",
      "code": "NR",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/nr.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/kyAGw6XEJgjSMsTK7",
      "flagIcon": "🇳🇷",
      "capital": "Yaren",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Argentina",
      "officialName": "Argentine Republic",
      "code": "AR",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ar.png",
      "continent": "South America",
      "timezone": "UTC-03:00",
      "locationInMap": "https://goo.gl/maps/Z9DXNxhf2o93kvyc6",
      "flagIcon": "🇦🇷",
      "capital": "Buenos Aires",
      "subregion": "South America"
    },
    {
      "commonName": "Pitcairn Islands",
      "officialName": "Pitcairn Group of Islands",
      "code": "PN",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/pn.png",
      "continent": "Oceania",
      "timezone": "UTC-08:00",
      "locationInMap": "https://goo.gl/maps/XGJMnMAigXjXcxSa7",
      "flagIcon": "🇵🇳",
      "capital": "Adamstown",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Wallis and Futuna",
      "officialName": "Territory of the Wallis and Futuna Islands",
      "code": "WF",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/wf.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/CzVqK74QYtbHv65r5",
      "flagIcon": "🇼🇫",
      "capital": "Mata-Utu",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Yemen",
      "officialName": "Republic of Yemen",
      "code": "YE",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ye.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/WCmE76HKcLideQQw7",
      "flagIcon": "🇾🇪",
      "capital": "Sana'a",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Slovakia",
      "officialName": "Slovak Republic",
      "code": "SK",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/sk.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/uNSH2wW4bLoZVYJj7",
      "flagIcon": "🇸🇰",
      "capital": "Bratislava",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Turks and Caicos Islands",
      "officialName": "Turks and Caicos Islands",
      "code": "TC",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/tc.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/R8VUDQfwZiFtvmyn8",
      "flagIcon": "🇹🇨",
      "capital": "Cockburn Town",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Sweden",
      "officialName": "Kingdom of Sweden",
      "code": "SE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/se.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/iqygE491ADVgnBW39",
      "flagIcon": "🇸🇪",
      "capital": "Stockholm",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Saint Helena",
      "officialName": "Saint Helena, Ascension and Tristan da Cunha",
      "code": "SH",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sh.png",
      "continent": "Africa",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/iv4VxnPzHkjLCJuc6",
      "flagIcon": "🇸🇭",
      "capital": "Jamestown",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Italy",
      "officialName": "Italian Republic",
      "code": "IT",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/it.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/8M1K27TDj7StTRTq8",
      "flagIcon": "🇮🇹",
      "capital": "Rome",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Brazil",
      "officialName": "Federative Republic of Brazil",
      "code": "BR",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/br.png",
      "continent": "South America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/waCKk21HeeqFzkNC9",
      "flagIcon": "🇧🇷",
      "capital": "Brasília",
      "subregion": "South America"
    },
    {
      "commonName": "South Sudan",
      "officialName": "Republic of South Sudan",
      "code": "SS",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ss.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/Zm1AYCXb9HSNF1P27",
      "flagIcon": "🇸🇸",
      "capital": "Juba",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Cyprus",
      "officialName": "Republic of Cyprus",
      "code": "CY",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/cy.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/77hPBRdLid8yD5Bm7",
      "flagIcon": "🇨🇾",
      "capital": "Nicosia",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Thailand",
      "officialName": "Kingdom of Thailand",
      "code": "TH",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/th.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/qeU6uqsfW4nCCwzw9",
      "flagIcon": "🇹🇭",
      "capital": "Bangkok",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Turkey",
      "officialName": "Republic of Turkey",
      "code": "TR",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/tr.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/dXFFraiUDfcB6Quk6",
      "flagIcon": "🇹🇷",
      "capital": "Ankara",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Bermuda",
      "officialName": "Bermuda",
      "code": "BM",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bm.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/NLsRGNjTzDghTtAJA",
      "flagIcon": "🇧🇲",
      "capital": "Hamilton",
      "subregion": "North America"
    },
    {
      "commonName": "Australia",
      "officialName": "Commonwealth of Australia",
      "code": "AU",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/au.png",
      "continent": "Oceania",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/DcjaDa7UbhnZTndH6",
      "flagIcon": "🇦🇺",
      "capital": "Canberra",
      "subregion": "Australia and New Zealand"
    },
    {
      "commonName": "Bangladesh",
      "officialName": "People's Republic of Bangladesh",
      "code": "BD",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/bd.png",
      "continent": "Asia",
      "timezone": "UTC+06:00",
      "locationInMap": "https://goo.gl/maps/op6gmLbHcvv6rLhH6",
      "flagIcon": "🇧🇩",
      "capital": "Dhaka",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Grenada",
      "officialName": "Grenada",
      "code": "GD",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gd.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/rqWyfUAt4xhvk1Zy9",
      "flagIcon": "🇬🇩",
      "capital": "St. George's",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Singapore",
      "officialName": "Republic of Singapore",
      "code": "SG",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/sg.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/QbQt9Y9b5KFzsahV6",
      "flagIcon": "🇸🇬",
      "capital": "Singapore",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Moldova",
      "officialName": "Republic of Moldova",
      "code": "MD",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/md.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/JjmyUuULujnDeFPf7",
      "flagIcon": "🇲🇩",
      "capital": "Chișinău",
      "subregion": "Eastern Europe"
    },
    {
      "commonName": "Mali",
      "officialName": "Republic of Mali",
      "code": "ML",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ml.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/u9mYJkCB19wyuzh27",
      "flagIcon": "🇲🇱",
      "capital": "Bamako",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Kenya",
      "officialName": "Republic of Kenya",
      "code": "KE",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ke.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/Ni9M7wcCxf8bJHLX8",
      "flagIcon": "🇰🇪",
      "capital": "Nairobi",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Uruguay",
      "officialName": "Oriental Republic of Uruguay",
      "code": "UY",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/uy.png",
      "continent": "South America",
      "timezone": "UTC-03:00",
      "locationInMap": "https://goo.gl/maps/tiQ9Baekb1jQtDSD9",
      "flagIcon": "🇺🇾",
      "capital": "Montevideo",
      "subregion": "South America"
    },
    {
      "commonName": "Switzerland",
      "officialName": "Swiss Confederation",
      "code": "CH",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ch.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/uVuZcXaxSx5jLyEC9",
      "flagIcon": "🇨🇭",
      "capital": "Bern",
      "subregion": "Western Europe"
    },
    {
      "commonName": "El Salvador",
      "officialName": "Republic of El Salvador",
      "code": "SV",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/sv.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/cZnCEi5sEMQtKKcB7",
      "flagIcon": "🇸🇻",
      "capital": "San Salvador",
      "subregion": "Central America"
    },
    {
      "commonName": "Chad",
      "officialName": "Republic of Chad",
      "code": "TD",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/td.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/ziUdAZ8skuNfx5Hx7",
      "flagIcon": "🇹🇩",
      "capital": "N'Djamena",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Greenland",
      "officialName": "Greenland",
      "code": "GL",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gl.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/j3289UPEQXt1ceSy8",
      "flagIcon": "🇬🇱",
      "capital": "Nuuk",
      "subregion": "North America"
    },
    {
      "commonName": "Belarus",
      "officialName": "Republic of Belarus",
      "code": "BY",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/by.png",
      "continent": "Europe",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/PJUDU3EBPSszCQcu6",
      "flagIcon": "🇧🇾",
      "capital": "Minsk",
      "subregion": "Eastern Europe"
    },
    {
      "commonName": "Ivory Coast",
      "officialName": "Republic of Côte d'Ivoire",
      "code": "CI",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ci.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/wKsmN7f5qAeNtGjP6",
      "flagIcon": "🇨🇮",
      "capital": "Yamoussoukro",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Lebanon",
      "officialName": "Lebanese Republic",
      "code": "LB",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/lb.png",
      "continent": "Asia",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/Sz5VCU8UFBqMyTdc9",
      "flagIcon": "🇱🇧",
      "capital": "Beirut",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Netherlands",
      "officialName": "Kingdom of the Netherlands",
      "code": "NL",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/nl.png",
      "continent": "Europe",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/Hv6zQswGhFxoVVBm6",
      "flagIcon": "🇳🇱",
      "capital": "Amsterdam",
      "subregion": "Western Europe"
    },
    {
      "commonName": "San Marino",
      "officialName": "Republic of San Marino",
      "code": "SM",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/sm.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/rxCVJjm8dVY93RPY8",
      "flagIcon": "🇸🇲",
      "capital": "City of San Marino",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Bhutan",
      "officialName": "Kingdom of Bhutan",
      "code": "BT",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/bt.png",
      "continent": "Asia",
      "timezone": "UTC+06:00",
      "locationInMap": "https://goo.gl/maps/VEfXXBftTFLUpNgp8",
      "flagIcon": "🇧🇹",
      "capital": "Thimphu",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Malaysia",
      "officialName": "Malaysia",
      "code": "MY",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/my.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/qrY1PNeUXGyXDcPy6",
      "flagIcon": "🇲🇾",
      "capital": "Kuala Lumpur",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Kazakhstan",
      "officialName": "Republic of Kazakhstan",
      "code": "KZ",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kz.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/8VohJGu7ShuzZYyeA",
      "flagIcon": "🇰🇿",
      "capital": "Nur-Sultan",
      "subregion": "Central Asia"
    },
    {
      "commonName": "Finland",
      "officialName": "Republic of Finland",
      "code": "FI",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/fi.png",
      "continent": "Europe",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/HjgWDCNKRAYHrkMn8",
      "flagIcon": "🇫🇮",
      "capital": "Helsinki",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Tunisia",
      "officialName": "Tunisian Republic",
      "code": "TN",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/tn.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/KgUmpZdUuNRaougs8",
      "flagIcon": "🇹🇳",
      "capital": "Tunis",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Gambia",
      "officialName": "Republic of the Gambia",
      "code": "GM",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/gm.png",
      "continent": "Africa",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/bbGBCxxtfD2A9Z4m6",
      "flagIcon": "🇬🇲",
      "capital": "Banjul",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Syria",
      "officialName": "Syrian Arab Republic",
      "code": "SY",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/sy.png",
      "continent": "Asia",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/Xe3VnFbwdb4nv2SM9",
      "flagIcon": "🇸🇾",
      "capital": "Damascus",
      "subregion": "Western Asia"
    },
    {
      "commonName": "French Southern and Antarctic Lands",
      "officialName": "Territory of the French Southern and Antarctic Lands",
      "code": "TF",
      "region": "Antarctic",
      "flag": "https://flagcdn.com/w320/tf.png",
      "continent": "Oceania",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/6ua6CX1m4w1xF2Em7",
      "flagIcon": "🇹🇫",
      "capital": "Port-aux-Français",
      "subregion": ""
    },
    {
      "commonName": "Norfolk Island",
      "officialName": "Territory of Norfolk Island",
      "code": "NF",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/nf.png",
      "continent": "Oceania",
      "timezone": "UTC+11:30",
      "locationInMap": "https://goo.gl/maps/pbvtm6XYd1iZbjky5",
      "flagIcon": "🇳🇫",
      "capital": "Kingston",
      "subregion": "Australia and New Zealand"
    },
    {
      "commonName": "Guinea",
      "officialName": "Republic of Guinea",
      "code": "GN",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/gn.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/8J5oM5sA4Ayr1ZYGA",
      "flagIcon": "🇬🇳",
      "capital": "Conakry",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Caribbean Netherlands",
      "officialName": "Bonaire, Sint Eustatius and Saba",
      "code": "BQ",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bq.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/4XVes1P6uEDTz77WA",
      "flagIcon": "🇧🇶",
      "capital": "Kralendijk",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Mozambique",
      "officialName": "Republic of Mozambique",
      "code": "MZ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/mz.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/xCLcY9fzU6x4Pueu5",
      "flagIcon": "🇲🇿",
      "capital": "Maputo",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Samoa",
      "officialName": "Independent State of Samoa",
      "code": "WS",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/ws.png",
      "continent": "Oceania",
      "timezone": "UTC+13:00",
      "locationInMap": "https://goo.gl/maps/CFC9fEFP9cfkYUBF9",
      "flagIcon": "🇼🇸",
      "capital": "Apia",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Taiwan",
      "officialName": "Republic of China (Taiwan)",
      "code": "TW",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/tw.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/HgMKFQjNadF3Wa6B6",
      "flagIcon": "🇹🇼",
      "capital": "Taipei",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "South Georgia",
      "officialName": "South Georgia and the South Sandwich Islands",
      "code": "GS",
      "region": "Antarctic",
      "flag": "https://flagcdn.com/w320/gs.png",
      "continent": "Oceania",
      "timezone": "UTC-02:00",
      "locationInMap": "https://goo.gl/maps/mJzdaBwKBbm2B81q9",
      "flagIcon": "🇬🇸",
      "capital": "King Edward Point",
      "subregion": ""
    },
    {
      "commonName": "North Korea",
      "officialName": "Democratic People's Republic of Korea",
      "code": "KP",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kp.png",
      "continent": "Asia",
      "timezone": "UTC+09:00",
      "locationInMap": "https://goo.gl/maps/9q5T2DMeH5JL7Tky6",
      "flagIcon": "🇰🇵",
      "capital": "Pyongyang",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "Djibouti",
      "officialName": "Republic of Djibouti",
      "code": "DJ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/dj.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/V1HWfzN3bS1kwf4C6",
      "flagIcon": "🇩🇯",
      "capital": "Djibouti",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Suriname",
      "officialName": "Republic of Suriname",
      "code": "SR",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/sr.png",
      "continent": "South America",
      "timezone": "UTC-03:00",
      "locationInMap": "https://goo.gl/maps/iy7TuQLSi4qgoBoG7",
      "flagIcon": "🇸🇷",
      "capital": "Paramaribo",
      "subregion": "South America"
    },
    {
      "commonName": "France",
      "officialName": "French Republic",
      "code": "FR",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/fr.png",
      "continent": "Europe",
      "timezone": "UTC-10:00",
      "locationInMap": "https://goo.gl/maps/g7QxxSFsWyTPKuzd7",
      "flagIcon": "🇫🇷",
      "capital": "Paris",
      "subregion": "Western Europe"
    },
    {
      "commonName": "Rwanda",
      "officialName": "Republic of Rwanda",
      "code": "RW",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/rw.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/j5xb5r7CLqjYbyP86",
      "flagIcon": "🇷🇼",
      "capital": "Kigali",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "South Korea",
      "officialName": "Republic of Korea",
      "code": "KR",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kr.png",
      "continent": "Asia",
      "timezone": "UTC+09:00",
      "locationInMap": "https://goo.gl/maps/7ecjaJXefjAQhxjGA",
      "flagIcon": "🇰🇷",
      "capital": "Seoul",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "Curaçao",
      "officialName": "Country of Curaçao",
      "code": "CW",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/cw.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/9D3hTeA3qKaRT7S16",
      "flagIcon": "🇨🇼",
      "capital": "Willemstad",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Jamaica",
      "officialName": "Jamaica",
      "code": "JM",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/jm.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/Z8mQ6jxnRQKFwJy9A",
      "flagIcon": "🇯🇲",
      "capital": "Kingston",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Maldives",
      "officialName": "Republic of the Maldives",
      "code": "MV",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/mv.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/MNAWGq9vEdbZ9vUV7",
      "flagIcon": "🇲🇻",
      "capital": "Malé",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Slovenia",
      "officialName": "Republic of Slovenia",
      "code": "SI",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/si.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/7zgFmswcCJh5L5D49",
      "flagIcon": "🇸🇮",
      "capital": "Ljubljana",
      "subregion": "Central Europe"
    },
    {
      "commonName": "Christmas Island",
      "officialName": "Territory of Christmas Island",
      "code": "CX",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/cx.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/ZC17hHsQZpShN5wk9",
      "flagIcon": "🇨🇽",
      "capital": "Flying Fish Cove",
      "subregion": "Australia and New Zealand"
    },
    {
      "commonName": "Virgin Islands",
      "officialName": "Virgin Islands of the United States",
      "code": "VI",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/vi.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/mBfreywj8dor6q4m9",
      "flagIcon": "🇻🇮",
      "capital": "Charlotte Amalie",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Paraguay",
      "officialName": "Republic of Paraguay",
      "code": "PY",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/py.png",
      "continent": "South America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/JtnqG73WJn1Gx6mz6",
      "flagIcon": "🇵🇾",
      "capital": "Asunción",
      "subregion": "South America"
    },
    {
      "commonName": "Indonesia",
      "officialName": "Republic of Indonesia",
      "code": "ID",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/id.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/9gfPupm5bffixiFJ6",
      "flagIcon": "🇮🇩",
      "capital": "Jakarta",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Madagascar",
      "officialName": "Republic of Madagascar",
      "code": "MG",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/mg.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/AHQh2ABBaFW6Ngj26",
      "flagIcon": "🇲🇬",
      "capital": "Antananarivo",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Iraq",
      "officialName": "Republic of Iraq",
      "code": "IQ",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/iq.png",
      "continent": "Asia",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/iL8Bmy1sUCW9fUk18",
      "flagIcon": "🇮🇶",
      "capital": "Baghdad",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Honduras",
      "officialName": "Republic of Honduras",
      "code": "HN",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/hn.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/BbeJK8Sk2VkMHbdF8",
      "flagIcon": "🇭🇳",
      "capital": "Tegucigalpa",
      "subregion": "Central America"
    },
    {
      "commonName": "Morocco",
      "officialName": "Kingdom of Morocco",
      "code": "MA",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ma.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/6oMv3dyBZg3iaXQ5A",
      "flagIcon": "🇲🇦",
      "capital": "Rabat",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Hong Kong",
      "officialName": "Hong Kong Special Administrative Region of the People's Republic of China",
      "code": "HK",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/hk.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/1sEnNmT47ffrC8MU8",
      "flagIcon": "🇭🇰",
      "capital": "City of Victoria",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "Antigua and Barbuda",
      "officialName": "Antigua and Barbuda",
      "code": "AG",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ag.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/fnye4wGJ1RzC9jpX9",
      "flagIcon": "🇦🇬",
      "capital": "Saint John's",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Sri Lanka",
      "officialName": "Democratic Socialist Republic of Sri Lanka",
      "code": "LK",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/lk.png",
      "continent": "Asia",
      "timezone": "UTC+05:30",
      "locationInMap": "https://goo.gl/maps/VkPHoeFSfgzRQCDv8",
      "flagIcon": "🇱🇰",
      "capital": "Sri Jayawardenepura Kotte",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Haiti",
      "officialName": "Republic of Haiti",
      "code": "HT",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/ht.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/9o13xtjuUdqFnHbn9",
      "flagIcon": "🇭🇹",
      "capital": "Port-au-Prince",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Cuba",
      "officialName": "Republic of Cuba",
      "code": "CU",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/cu.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/1dDw1QfZspfMUTm99",
      "flagIcon": "🇨🇺",
      "capital": "Havana",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Tajikistan",
      "officialName": "Republic of Tajikistan",
      "code": "TJ",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/tj.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/8rQgW88jEXijhVb58",
      "flagIcon": "🇹🇯",
      "capital": "Dushanbe",
      "subregion": "Central Asia"
    },
    {
      "commonName": "Cook Islands",
      "officialName": "Cook Islands",
      "code": "CK",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/ck.png",
      "continent": "Oceania",
      "timezone": "UTC-10:00",
      "locationInMap": "https://goo.gl/maps/nrGZrvWRGB4WHgDC9",
      "flagIcon": "🇨🇰",
      "capital": "Avarua",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Colombia",
      "officialName": "Republic of Colombia",
      "code": "CO",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/co.png",
      "continent": "South America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/RdwTG8e7gPwS62oR6",
      "flagIcon": "🇨🇴",
      "capital": "Bogotá",
      "subregion": "South America"
    },
    {
      "commonName": "Micronesia",
      "officialName": "Federated States of Micronesia",
      "code": "FM",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/fm.png",
      "continent": "Oceania",
      "timezone": "UTC+10:00",
      "locationInMap": "https://goo.gl/maps/LLcnofC5LxZsJXTo8",
      "flagIcon": "🇫🇲",
      "capital": "Palikir",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Northern Mariana Islands",
      "officialName": "Commonwealth of the Northern Mariana Islands",
      "code": "MP",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/mp.png",
      "continent": "Oceania",
      "timezone": "UTC+10:00",
      "locationInMap": "https://goo.gl/maps/cpZ67knoRAcfu1417",
      "flagIcon": "🇲🇵",
      "capital": "Saipan",
      "subregion": "Micronesia"
    },
    {
      "commonName": "Saint Kitts and Nevis",
      "officialName": "Federation of Saint Christopher and Nevis",
      "code": "KN",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/kn.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/qiaVwcLVTXX3eoTNA",
      "flagIcon": "🇰🇳",
      "capital": "Basseterre",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Uzbekistan",
      "officialName": "Republic of Uzbekistan",
      "code": "UZ",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/uz.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/AJpo6MjMx23qSWCz8",
      "flagIcon": "🇺🇿",
      "capital": "Tashkent",
      "subregion": "Central Asia"
    },
    {
      "commonName": "Gibraltar",
      "officialName": "Gibraltar",
      "code": "GI",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/gi.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/CEoHAs1t6byCBhHFA",
      "flagIcon": "🇬🇮",
      "capital": "Gibraltar",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Ireland",
      "officialName": "Republic of Ireland",
      "code": "IE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ie.png",
      "continent": "Europe",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/hxd1BKxgpchStzQC6",
      "flagIcon": "🇮🇪",
      "capital": "Dublin",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Peru",
      "officialName": "Republic of Peru",
      "code": "PE",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/pe.png",
      "continent": "South America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/uDWEUaXNcZTng1fP6",
      "flagIcon": "🇵🇪",
      "capital": "Lima",
      "subregion": "South America"
    },
    {
      "commonName": "Pakistan",
      "officialName": "Islamic Republic of Pakistan",
      "code": "PK",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/pk.png",
      "continent": "Asia",
      "timezone": "UTC+05:00",
      "locationInMap": "https://goo.gl/maps/5LYujdfR5yLUXoERA",
      "flagIcon": "🇵🇰",
      "capital": "Islamabad",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Chile",
      "officialName": "Republic of Chile",
      "code": "CL",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/cl.png",
      "continent": "South America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/XboxyNHh2fAjCPNn9",
      "flagIcon": "🇨🇱",
      "capital": "Santiago",
      "subregion": "South America"
    },
    {
      "commonName": "Zambia",
      "officialName": "Republic of Zambia",
      "code": "ZM",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/zm.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/mweBcqvW8TppZW6q9",
      "flagIcon": "🇿🇲",
      "capital": "Lusaka",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Saint Lucia",
      "officialName": "Saint Lucia",
      "code": "LC",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/lc.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/4HhJ2jkPdSL9BPRcA",
      "flagIcon": "🇱🇨",
      "capital": "Castries",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Seychelles",
      "officialName": "Republic of Seychelles",
      "code": "SC",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sc.png",
      "continent": "Africa",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/aqCcy2TKh5TV5MAX8",
      "flagIcon": "🇸🇨",
      "capital": "Victoria",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Benin",
      "officialName": "Republic of Benin",
      "code": "BJ",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/bj.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/uMw1BsHEXQYgVFFu6",
      "flagIcon": "🇧🇯",
      "capital": "Porto-Novo",
      "subregion": "Western Africa"
    },
    {
      "commonName": "United Kingdom",
      "officialName": "United Kingdom of Great Britain and Northern Ireland",
      "code": "GB",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/gb.png",
      "continent": "Europe",
      "timezone": "UTC-08:00",
      "locationInMap": "https://goo.gl/maps/FoDtc3UKMkFsXAjHA",
      "flagIcon": "🇬🇧",
      "capital": "London",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Costa Rica",
      "officialName": "Republic of Costa Rica",
      "code": "CR",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/cr.png",
      "continent": "North America",
      "timezone": "UTC-06:00",
      "locationInMap": "https://goo.gl/maps/RFiwytjvNrpfKN7k6",
      "flagIcon": "🇨🇷",
      "capital": "San José",
      "subregion": "Central America"
    },
    {
      "commonName": "Comoros",
      "officialName": "Union of the Comoros",
      "code": "KM",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/km.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/eas4GP28C1GyStnu6",
      "flagIcon": "🇰🇲",
      "capital": "Moroni",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Iceland",
      "officialName": "Iceland",
      "code": "IS",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/is.png",
      "continent": "Europe",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/WxFWSQuc3oamNxoE6",
      "flagIcon": "🇮🇸",
      "capital": "Reykjavik",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Japan",
      "officialName": "Japan",
      "code": "JP",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/jp.png",
      "continent": "Asia",
      "timezone": "UTC+09:00",
      "locationInMap": "https://goo.gl/maps/NGTLSCSrA8bMrvnX9",
      "flagIcon": "🇯🇵",
      "capital": "Tokyo",
      "subregion": "Eastern Asia"
    },
    {
      "commonName": "Vatican City",
      "officialName": "Vatican City State",
      "code": "VA",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/va.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/DTKvw5Bd1QZaDZmE8",
      "flagIcon": "🇻🇦",
      "capital": "Vatican City",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "British Virgin Islands",
      "officialName": "Virgin Islands",
      "code": "VG",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/vg.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/49C9cSesNVAR9DQk8",
      "flagIcon": "🇻🇬",
      "capital": "Road Town",
      "subregion": "Caribbean"
    },
    {
      "commonName": "New Caledonia",
      "officialName": "New Caledonia",
      "code": "NC",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/nc.png",
      "continent": "Oceania",
      "timezone": "UTC+11:00",
      "locationInMap": "https://goo.gl/maps/cBhtCeMdob4U7FRU9",
      "flagIcon": "🇳🇨",
      "capital": "Nouméa",
      "subregion": "Melanesia"
    },
    {
      "commonName": "Fiji",
      "officialName": "Republic of Fiji",
      "code": "FJ",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/fj.png",
      "continent": "Oceania",
      "timezone": "UTC+12:00",
      "locationInMap": "https://goo.gl/maps/r9fhDqoLZdg1zmE99",
      "flagIcon": "🇫🇯",
      "capital": "Suva",
      "subregion": "Melanesia"
    },
    {
      "commonName": "Bosnia and Herzegovina",
      "officialName": "Bosnia and Herzegovina",
      "code": "BA",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ba.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://www.google.com/maps/place/Bosnia+and+Herzegovina",
      "flagIcon": "🇧🇦",
      "capital": "Sarajevo",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Cocos Islands",
      "officialName": "Territory of the Cocos (Keeling) Islands",
      "code": "CC",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/cc.png",
      "continent": "Asia",
      "timezone": "UTC+06:30",
      "locationInMap": "https://goo.gl/maps/3eCdKVpVfMcZyKcK6",
      "flagIcon": "🇨🇨",
      "capital": "West Island",
      "subregion": "Australia and New Zealand"
    },
    {
      "commonName": "Western Sahara",
      "officialName": "Sahrawi Arab Democratic Republic",
      "code": "EH",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/eh.png",
      "continent": "Africa",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/7nU3mB69vP6zQp7A8",
      "flagIcon": "🇪🇭",
      "capital": "El Aaiún",
      "subregion": "Northern Africa"
    },
    {
      "commonName": "Mexico",
      "officialName": "United Mexican States",
      "code": "MX",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/mx.png",
      "continent": "North America",
      "timezone": "UTC-08:00",
      "locationInMap": "https://goo.gl/maps/s5g7imNPMDEePxzbA",
      "flagIcon": "🇲🇽",
      "capital": "Mexico City",
      "subregion": "North America"
    },
    {
      "commonName": "Cambodia",
      "officialName": "Kingdom of Cambodia",
      "code": "KH",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/kh.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/nztQtFSrUXZymJaW8",
      "flagIcon": "🇰🇭",
      "capital": "Phnom Penh",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Saint Vincent and the Grenadines",
      "officialName": "Saint Vincent and the Grenadines",
      "code": "VC",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/vc.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/wMbnMqjG37FMnrwf7",
      "flagIcon": "🇻🇨",
      "capital": "Kingstown",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Iran",
      "officialName": "Islamic Republic of Iran",
      "code": "IR",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ir.png",
      "continent": "Asia",
      "timezone": "UTC+03:30",
      "locationInMap": "https://goo.gl/maps/dMgEGuacBPGYQnjY7",
      "flagIcon": "🇮🇷",
      "capital": "Tehran",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Malta",
      "officialName": "Republic of Malta",
      "code": "MT",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/mt.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/skXCqguxDxxEKVk47",
      "flagIcon": "🇲🇹",
      "capital": "Valletta",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Serbia",
      "officialName": "Republic of Serbia",
      "code": "RS",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/rs.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/2Aqof7aV2Naq8YEK8",
      "flagIcon": "🇷🇸",
      "capital": "Belgrade",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "United Arab Emirates",
      "officialName": "United Arab Emirates",
      "code": "AE",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/ae.png",
      "continent": "Asia",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/AZZTDA6GzVAnKMVd8",
      "flagIcon": "🇦🇪",
      "capital": "Abu Dhabi",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Azerbaijan",
      "officialName": "Republic of Azerbaijan",
      "code": "AZ",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/az.png",
      "continent": "Asia",
      "timezone": "UTC+04:00",
      "locationInMap": "https://goo.gl/maps/az3Zz7ar2aoB9AUc6",
      "flagIcon": "🇦🇿",
      "capital": "Baku",
      "subregion": "Western Asia"
    },
    {
      "commonName": "French Polynesia",
      "officialName": "French Polynesia",
      "code": "PF",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/pf.png",
      "continent": "Oceania",
      "timezone": "UTC-10:00",
      "locationInMap": "https://goo.gl/maps/xgg6BQTRyeQg4e1m6",
      "flagIcon": "🇵🇫",
      "capital": "Papeetē",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Vanuatu",
      "officialName": "Republic of Vanuatu",
      "code": "VU",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/vu.png",
      "continent": "Oceania",
      "timezone": "UTC+11:00",
      "locationInMap": "https://goo.gl/maps/hwAjehcT7VfvP5zJ8",
      "flagIcon": "🇻🇺",
      "capital": "Port Vila",
      "subregion": "Melanesia"
    },
    {
      "commonName": "Niger",
      "officialName": "Republic of Niger",
      "code": "NE",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ne.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/VKNU2TLsZcgxM49c8",
      "flagIcon": "🇳🇪",
      "capital": "Niamey",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Eritrea",
      "officialName": "State of Eritrea",
      "code": "ER",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/er.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/HRyqUpnPwwG6jY5j6",
      "flagIcon": "🇪🇷",
      "capital": "Asmara",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Central African Republic",
      "officialName": "Central African Republic",
      "code": "CF",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/cf.png",
      "continent": "Africa",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/51V8dsi2rGYC9n3c9",
      "flagIcon": "🇨🇫",
      "capital": "Bangui",
      "subregion": "Middle Africa"
    },
    {
      "commonName": "Israel",
      "officialName": "State of Israel",
      "code": "IL",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/il.png",
      "continent": "Asia",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/6UY1AH8XeafVwdC97",
      "flagIcon": "🇮🇱",
      "capital": "Jerusalem",
      "subregion": "Western Asia"
    },
    {
      "commonName": "Nepal",
      "officialName": "Federal Democratic Republic of Nepal",
      "code": "NP",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/np.png",
      "continent": "Asia",
      "timezone": "UTC+05:45",
      "locationInMap": "https://goo.gl/maps/UMj2zpbQp7B5c3yT7",
      "flagIcon": "🇳🇵",
      "capital": "Kathmandu",
      "subregion": "Southern Asia"
    },
    {
      "commonName": "Panama",
      "officialName": "Republic of Panama",
      "code": "PA",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/pa.png",
      "continent": "North America",
      "timezone": "UTC-05:00",
      "locationInMap": "https://goo.gl/maps/sEN7sKqeawa5oPNLA",
      "flagIcon": "🇵🇦",
      "capital": "Panama City",
      "subregion": "Central America"
    },
    {
      "commonName": "Guernsey",
      "officialName": "Bailiwick of Guernsey",
      "code": "GG",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/gg.png",
      "continent": "Europe",
      "timezone": "UTC+00:00",
      "locationInMap": "https://goo.gl/maps/6kXnQU5QvEZMD9VB7",
      "flagIcon": "🇬🇬",
      "capital": "St. Peter Port",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Solomon Islands",
      "officialName": "Solomon Islands",
      "code": "SB",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/sb.png",
      "continent": "Oceania",
      "timezone": "UTC+11:00",
      "locationInMap": "https://goo.gl/maps/JbPkx86Ywjv8C1n8A",
      "flagIcon": "🇸🇧",
      "capital": "Honiara",
      "subregion": "Melanesia"
    },
    {
      "commonName": "Zimbabwe",
      "officialName": "Republic of Zimbabwe",
      "code": "ZW",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/zw.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/M26BqdwQctqxXS65A",
      "flagIcon": "🇿🇼",
      "capital": "Harare",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "Aruba",
      "officialName": "Aruba",
      "code": "AW",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/aw.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/8hopbQqifHAgyZyg8",
      "flagIcon": "🇦🇼",
      "capital": "Oranjestad",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Brunei",
      "officialName": "Nation of Brunei, Abode of Peace",
      "code": "BN",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/bn.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/4jb4CqBXhr8vNh579",
      "flagIcon": "🇧🇳",
      "capital": "Bandar Seri Begawan",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Denmark",
      "officialName": "Kingdom of Denmark",
      "code": "DK",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/dk.png",
      "continent": "Europe",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/UddGPN7hAyrtpFiT6",
      "flagIcon": "🇩🇰",
      "capital": "Copenhagen",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Belgium",
      "officialName": "Kingdom of Belgium",
      "code": "BE",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/be.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/UQQzat85TCtPRXAL8",
      "flagIcon": "🇧🇪",
      "capital": "Brussels",
      "subregion": "Western Europe"
    },
    {
      "commonName": "French Guiana",
      "officialName": "Guiana",
      "code": "GF",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gf.png",
      "continent": "South America",
      "timezone": "UTC-03:00",
      "locationInMap": "https://goo.gl/maps/NJawFwMzG7YtCrVP7",
      "flagIcon": "🇬🇫",
      "capital": "Cayenne",
      "subregion": "South America"
    },
    {
      "commonName": "Laos",
      "officialName": "Lao People's Democratic Republic",
      "code": "LA",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/la.png",
      "continent": "Asia",
      "timezone": "UTC+07:00",
      "locationInMap": "https://goo.gl/maps/F3asVB7sRKgSnwbE7",
      "flagIcon": "🇱🇦",
      "capital": "Vientiane",
      "subregion": "South-Eastern Asia"
    },
    {
      "commonName": "Tonga",
      "officialName": "Kingdom of Tonga",
      "code": "TO",
      "region": "Oceania",
      "flag": "https://flagcdn.com/w320/to.png",
      "continent": "Oceania",
      "timezone": "UTC+13:00",
      "locationInMap": "https://goo.gl/maps/p5YALBY2QdEzswRo7",
      "flagIcon": "🇹🇴",
      "capital": "Nuku'alofa",
      "subregion": "Polynesia"
    },
    {
      "commonName": "Andorra",
      "officialName": "Principality of Andorra",
      "code": "AD",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/ad.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/JqAnacWE2qEznKgw7",
      "flagIcon": "🇦🇩",
      "capital": "Andorra la Vella",
      "subregion": "Southern Europe"
    },
    {
      "commonName": "Guadeloupe",
      "officialName": "Guadeloupe",
      "code": "GP",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/gp.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/Dy9R2EufJtoWm8UN9",
      "flagIcon": "🇬🇵",
      "capital": "Basse-Terre",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Martinique",
      "officialName": "Martinique",
      "code": "MQ",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/mq.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/87ER7sDAFU7JjcvR6",
      "flagIcon": "🇲🇶",
      "capital": "Fort-de-France",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Lesotho",
      "officialName": "Kingdom of Lesotho",
      "code": "LS",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/ls.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/H8gJi5mL4Cmd1SF28",
      "flagIcon": "🇱🇸",
      "capital": "Maseru",
      "subregion": "Southern Africa"
    },
    {
      "commonName": "Dominica",
      "officialName": "Commonwealth of Dominica",
      "code": "DM",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/dm.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/HSKdHYpFC8oHHuyV7",
      "flagIcon": "🇩🇲",
      "capital": "Roseau",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Somalia",
      "officialName": "Federal Republic of Somalia",
      "code": "SO",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/so.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/8of8q7D1a8p7R6Fc9",
      "flagIcon": "🇸🇴",
      "capital": "Mogadishu",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Croatia",
      "officialName": "Republic of Croatia",
      "code": "HR",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/hr.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/qSG6xTKUmrYpwmGQ6",
      "flagIcon": "🇭🇷",
      "capital": "Zagreb",
      "subregion": "Southeast Europe"
    },
    {
      "commonName": "Sierra Leone",
      "officialName": "Republic of Sierra Leone",
      "code": "SL",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sl.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/jhacar85oq9QaeKB7",
      "flagIcon": "🇸🇱",
      "capital": "Freetown",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Saint Barthélemy",
      "officialName": "Collectivity of Saint Barthélemy",
      "code": "BL",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/bl.png",
      "continent": "North America",
      "timezone": "UTC-04:00",
      "locationInMap": "https://goo.gl/maps/Mc7GqH466S7AAk297",
      "flagIcon": "🇧🇱",
      "capital": "Gustavia",
      "subregion": "Caribbean"
    },
    {
      "commonName": "Svalbard and Jan Mayen",
      "officialName": "Svalbard og Jan Mayen",
      "code": "SJ",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/sj.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/L2wyyn3cQ16PzQ5J8",
      "flagIcon": "🇸🇯",
      "capital": "Longyearbyen",
      "subregion": "Northern Europe"
    },
    {
      "commonName": "Saint Pierre and Miquelon",
      "officialName": "Saint Pierre and Miquelon",
      "code": "PM",
      "region": "Americas",
      "flag": "https://flagcdn.com/w320/pm.png",
      "continent": "North America",
      "timezone": "UTC-03:00",
      "locationInMap": "https://goo.gl/maps/bUM8Yc8pA8ghyhmt6",
      "flagIcon": "🇵🇲",
      "capital": "Saint-Pierre",
      "subregion": "North America"
    },
    {
      "commonName": "Burundi",
      "officialName": "Republic of Burundi",
      "code": "BI",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/bi.png",
      "continent": "Africa",
      "timezone": "UTC+02:00",
      "locationInMap": "https://goo.gl/maps/RXPWoRrB9tfrJpUG7",
      "flagIcon": "🇧🇮",
      "capital": "Gitega",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Senegal",
      "officialName": "Republic of Senegal",
      "code": "SN",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/sn.png",
      "continent": "Africa",
      "timezone": "UTC",
      "locationInMap": "https://goo.gl/maps/o5f1uD5nyihCL3HCA",
      "flagIcon": "🇸🇳",
      "capital": "Dakar",
      "subregion": "Western Africa"
    },
    {
      "commonName": "Ethiopia",
      "officialName": "Federal Democratic Republic of Ethiopia",
      "code": "ET",
      "region": "Africa",
      "flag": "https://flagcdn.com/w320/et.png",
      "continent": "Africa",
      "timezone": "UTC+03:00",
      "locationInMap": "https://goo.gl/maps/2Q4hQWCbhuZLj3fG6",
      "flagIcon": "🇪🇹",
      "capital": "Addis Ababa",
      "subregion": "Eastern Africa"
    },
    {
      "commonName": "Luxembourg",
      "officialName": "Grand Duchy of Luxembourg",
      "code": "LU",
      "region": "Europe",
      "flag": "https://flagcdn.com/w320/lu.png",
      "continent": "Europe",
      "timezone": "UTC+01:00",
      "locationInMap": "https://goo.gl/maps/L6b2AgndgHprt2Ko9",
      "flagIcon": "🇱🇺",
      "capital": "Luxembourg",
      "subregion": "Western Europe"
    },
    {
      "commonName": "China",
      "officialName": "People's Republic of China",
      "code": "CN",
      "region": "Asia",
      "flag": "https://flagcdn.com/w320/cn.png",
      "continent": "Asia",
      "timezone": "UTC+08:00",
      "locationInMap": "https://goo.gl/maps/p9qC6vgiFRRXzvGi7",
      "flagIcon": "🇨🇳",
      "capital": "Beijing",
      "subregion": "Eastern Asia"
    }
  ]